# Data Cleaning

# Question 1:

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/rileywheadon/uss-x-dsci-datathon-datasets/refs/heads/master/bad_weather_1.csv"

df = pd.read_csv(url)

In [2]:
df.to_csv('raw_df.csv',index=False)

In [3]:
df.head()

  station_id            timestamp  temp_c     lat      lon
0     YVR-01           2025-01-01   -14.2  49.246 -123.116
1     YVR-01           2025/01/01    -6.6  49.246 -123.116
2     YVR-01   2025-01-01 08:28AM   -19.7  49.246 -123.116
3     YVR-01           2025-01-01   -10.7  49.246 -123.116
4     YVR-01  2025-01-01 16:42:03   -15.8  49.246 -123.116

In [4]:
df

     station_id            timestamp  temp_c     lat      lon
0        YVR-01           2025-01-01   -14.2  49.246 -123.116
1        YVR-01           2025/01/01    -6.6  49.246 -123.116
2        YVR-01   2025-01-01 08:28AM   -19.7  49.246 -123.116
3        YVR-01           2025-01-01   -10.7  49.246 -123.116
4        YVR-01  2025-01-01 16:42:03   -15.8  49.246 -123.116
...         ...                  ...     ...     ...      ...
2995     YVR-01   2026-05-15 04:35AM     4.4  49.246 -123.116
2996     YVR-01   2026-05-15 08:02AM     0.9  49.246 -123.116
2997     YVR-01           2026/05/15     7.4  49.246 -123.116
2998     YVR-01           2026-05-15    -2.9  49.246 -123.116
2999     YVR-01     2026-05-15 20:32     2.4  49.246 -123.116

[3000 rows x 5 columns]

In [5]:
df['timestamp'] = pd.to_datetime(df['timestamp'], format='mixed', errors='raise')
df.loc[df['timestamp'].dt.time == pd.Timestamp('00:00:00').time(), 'timestamp'] += pd.Timedelta(hours=12)
df['timestamp'] = df['timestamp'].dt.strftime('%Y-%m-%d %H:%M')
df

     station_id         timestamp  temp_c     lat      lon
0        YVR-01  2025-01-01 12:00   -14.2  49.246 -123.116
1        YVR-01  2025-01-01 12:00    -6.6  49.246 -123.116
2        YVR-01  2025-01-01 08:28   -19.7  49.246 -123.116
3        YVR-01  2025-01-01 12:00   -10.7  49.246 -123.116
4        YVR-01  2025-01-01 16:42   -15.8  49.246 -123.116
...         ...               ...     ...     ...      ...
2995     YVR-01  2026-05-15 04:35     4.4  49.246 -123.116
2996     YVR-01  2026-05-15 08:02     0.9  49.246 -123.116
2997     YVR-01  2026-05-15 12:00     7.4  49.246 -123.116
2998     YVR-01  2026-05-15 12:00    -2.9  49.246 -123.116
2999     YVR-01  2026-05-15 20:32     2.4  49.246 -123.116

[3000 rows x 5 columns]

In [6]:
df.to_csv('df1.csv',index=False)

# Question 2:

In [7]:
url_2 = 'https://raw.githubusercontent.com/rileywheadon/uss-x-dsci-datathon-datasets/refs/heads/master/bad_weather_2.csv'

df2 = pd.read_csv(url_2)

In [8]:

df2['timestamp'] = pd.to_datetime(df2['timestamp'], format='mixed', errors='raise')
df2.loc[df2['timestamp'].dt.time == pd.Timestamp('00:00:00').time(), 'timestamp'] += pd.Timedelta(hours=12)
# df2['timestamp'] = pd.to_datetime(df2['timestamp'], format='%Y-%m-%d %H:%M', errors='raise')
# df2['timestamp'] = df2['timestamp'].dt.strftime('%Y-%m-%d %H:%M')
df2

      station_id           timestamp  temp_c      lat       lon
0         YVR-01 2025-01-01 12:00:00   -14.2  49.2460 -123.1160
1         YVR-01 2025-01-01 12:00:00    -6.6  49.2460 -123.1160
2         YVR-01 2025-01-01 08:28:00   -19.7  49.2460 -123.1160
3         YVR-01 2025-01-01 12:00:00   -10.7  49.2460 -123.1160
4         YVR-01 2025-01-01 16:42:03   -15.8  49.2460 -123.1160
...          ...                 ...     ...      ...       ...
14995     LHR-01 2026-05-15 04:35:00     4.4  51.4775   -0.4614
14996     LHR-01 2026-05-15 08:02:00     0.9  51.4775   -0.4614
14997     LHR-01 2026-05-15 12:00:00     7.4  51.4775   -0.4614
14998     LHR-01 2026-05-15 12:00:00    -2.9  51.4775   -0.4614
14999     LHR-01 2026-05-15 20:32:00     2.4  51.4775   -0.4614

[15000 rows x 5 columns]

In [9]:
df2

      station_id           timestamp  temp_c      lat       lon
0         YVR-01 2025-01-01 12:00:00   -14.2  49.2460 -123.1160
1         YVR-01 2025-01-01 12:00:00    -6.6  49.2460 -123.1160
2         YVR-01 2025-01-01 08:28:00   -19.7  49.2460 -123.1160
3         YVR-01 2025-01-01 12:00:00   -10.7  49.2460 -123.1160
4         YVR-01 2025-01-01 16:42:03   -15.8  49.2460 -123.1160
...          ...                 ...     ...      ...       ...
14995     LHR-01 2026-05-15 04:35:00     4.4  51.4775   -0.4614
14996     LHR-01 2026-05-15 08:02:00     0.9  51.4775   -0.4614
14997     LHR-01 2026-05-15 12:00:00     7.4  51.4775   -0.4614
14998     LHR-01 2026-05-15 12:00:00    -2.9  51.4775   -0.4614
14999     LHR-01 2026-05-15 20:32:00     2.4  51.4775   -0.4614

[15000 rows x 5 columns]

In [10]:
df2.columns

Index(['station_id', 'timestamp', 'temp_c', 'lat', 'lon'], dtype='object')

In [11]:
from tzfpy import get_tz

df2['timezone'] = df2.apply(
    lambda row: get_tz(row['lon'], row['lat']), 
    axis=1
)

In [12]:
def localize_and_convert_to_utc(row):
    
    localized_time = row['timestamp'].tz_localize(row['timezone'], ambiguous='NaT', nonexistent='NaT')
    
    utc_time = localized_time.tz_convert('UTC')
    return utc_time

df2['timestamp_utc'] = df2.apply(localize_and_convert_to_utc, axis=1)
df2['timestamp_utc'] = df2['timestamp_utc'].dt.strftime('%Y-%m-%d %H:%M')
df2['timestamp'] = df2['timestamp'].dt.strftime('%Y-%m-%d %H:%M')

In [13]:
df2.to_csv('df2.csv',index=False)